A: Accuracy
B: Honesty
C: Explainability
D: Physical_Safety
E: Psychological_Safety
F: Compassion
G: Fair_Process
H: Equal_Outcomes
I: Freedom
J: Social_Duty
K: Trust_Institutions
L: Trust_Self
M: Ideal_Effectiveness
N: Real_Effectiveness
O: Harmony
P: Loyalty
Q: Economics
R: Sustainability
S: Property_Rights
T: Animal_Rights
U: Childrens_Rights
V: Exploration
W: Innovation
X: Tradition
Y: Risk_Taking
Z: Caution
AA: Privacy
AB: Accountability